apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app-go
spec:
  ingressClassName: nginx
  rules:
  - host: "web-app-go.local"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: web-app-go
            port:
              number: 80

